Repository IBM/clai, pull requests merged in 2020-05, with the labels that each got.

#61 zos-extension to nlc2cmd
  .gitignore
  clai/server/plugins/nlc2cmd/README.md
  clai/server/plugins/nlc2cmd/manifest.properties
  clai/server/plugins/nlc2cmd/remote/Procfile
  clai/server/plugins/nlc2cmd/remote/README.md
  clai/server/plugins/nlc2cmd/remote/config.json
  clai/server/plugins/nlc2cmd/remote/manifest.yml
  clai/server/plugins/nlc2cmd/remote/requirements.txt
  clai/server/plugins/nlc2cmd/remote/run.py
  clai/server/plugins/nlc2cmd/remote/runtime.txt
  clai/server/plugins/nlc2cmd/wa_skills/README.md
  clai/server/plugins/nlc2cmd/wa_skills/__init__.py
  clai/server/plugins/nlc2cmd/wa_skills/cloudbot.py
  clai/server/plugins/nlc2cmd/wa_skills/config.json
  clai/server/plugins/nlc2cmd/wa_skills/grepbot.py
  clai/server/plugins/nlc2cmd/wa_skills/tarbot.py
  clai/server/plugins/nlc2cmd/wa_skills/utils.py
  clai/server/plugins/nlc2cmd/wa_skills/zosbot.py
  requirements.txt
  test-requirements.txt
Labels: feature request, skill

#69 zosbot update
  Dockerfile.CLAI
  clai/server/plugins/nlc2cmd/wa_skills/zosbot.py
  test_integration/docker/centos/Dockerfile
  test_integration/docker/centos/Dockerfile.no.install
  test_integration/test_skill_nlc2cmd.py
Labels: enhancement

#54 Emulator fix
  clai/emulator/clai_emulator.py
  requirements-emulator.sh
  requirements-emulator.txt
Labels: bug
